version: '3'
services:
  web:
    image: dustinphan/practice_docker_cloud:web0-oct-31
    deploy:
      replicas: 2 # used for load balancing
      resources:
        limits:
          cpus: "0.05"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
