version: '3'
services:
  web:
    image: dustinphan/practice_docker_cloud:web0-oct-31
    deploy:
      replicas: 5 # used for load balancing
      resources:
        limits:
          cpus: "0.05"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
  visualizer:
    image: dockersamples/visulizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
